apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dr-oauth2-proxy-istio-mutual
  namespace: demo
spec:
  host: oauth2-proxy.demo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: dr-demo-app-istio-mutual
  namespace: demo
spec:
  host: demo-app.demo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
